package me.deprilula28.WebRebel.socket;

public enum LogType{
	
	ASSERT, CLEAR, COUNT, DEBUG, DIR, DIRXML, ERROR, EXCEPTION, GROUP, GROUPCOLLAPSED, GROUPEND, INFO, PROFILE, PROFILEEND, TABLE, TIME, TIMEEND, TIMESTAMP, TRACE, WARN, LOG
	
}
