package me.deprilula28.WebRebel;

public enum ActionType{
	
	CLIENT_HANDSHAKE, CLIENT_REQUEST_CODE_EDIT_PERM, CLIENT_CODE_EDIT, CLIENT_CONSOLE_LOG, CLIENT_PONG, CLIENT_ERROR,
	SERVER_ERROR_RESPONSE, SERVER_HANDSHAKE, SERVER_CODE_UPDATE, SERVER_FILE_DELETE, SERVER_PING, SERVER_CLIENT_PING_INFO;
	
}
